name: gtbook
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyter-book=0.12.1
  - python-graphviz
  - ipywidgets>=7.5
  - pandas
  - matplotlib
  - pip
  - pip:
      - plotly==5.5.0 # in pip for binder
      - kaleido # needed for png output :-(
      - gtbook
