name: deploy-book

# Only run this when the master branch changes
on:
  push:
    branches:
      - main

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
# If using conda lock, re-generate conda-lock file with:
# > conda-lock -f environment.yml -p linux-64
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    env:
      CONDA_LOCK: false
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - name: Activate conda env with conda.lock
        if: env.CONDA_LOCK == 'true'
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          auto-activate-base: false
          activate-environment: gtbook
          python-version: 3.9
          environment-file: conda-linux-64.lock

      - name: Activate conda env with environment.yml
        if: env.CONDA_LOCK == 'false'
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: false
          auto-activate-base: false
          activate-environment: gtbook
          python-version: 3.9
          environment-file: environment.yml

      - run: conda info --envs
        if: env.CONDA_LOCK == 'false'
        name: Check active env

      - run: conda list
        if: env.CONDA_LOCK == 'false'
        name: Check versions

      - run: pip install plotly==5.5.0
        if: env.CONDA_LOCK == 'true'
        name: Install plotly

      - run: pip install gtbook
        if: env.CONDA_LOCK == 'true'
        name: Install gtbook

      - name: Build Frank and Seth's book
        run: |
          jupyter-book clean .
          touch *.ipynb
          jupyter-book build .

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
          cname: www.roboticsbook.org
